using FeiSharpStudio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FeiSharpTerminal3._1
{
    public static class FeiSharpKeywords
    {
        public static readonly Dictionary<string, Token> KeywordMap =
            new Dictionary<string, Token>(50, StringComparer.OrdinalIgnoreCase)
            {
                ["print"] = new Token(TokenTypes.Keyword, "print"),
                ["printnl"] = new Token(TokenTypes.Keyword, "printnl"),
                ["gethtml"] = new Token(TokenTypes.Keyword, "gethtml"),
                ["var"] = new Token(TokenTypes.Keyword, "var"),
                ["set"] = new Token(TokenTypes.Keyword, "var"),
                ["let"] = new Token(TokenTypes.Keyword, "var"),
                ["dim"] = new Token(TokenTypes.Keyword, "var"),
                ["variable"] = new Token(TokenTypes.Keyword, "var"),
                ["field"] = new Token(TokenTypes.Keyword, "var"),
                ["datadef"] = new Token(TokenTypes.Keyword, "var"),
                ["init"] = new Token(TokenTypes.Keyword, "init"),
                ["setsf"] = new Token(TokenTypes.Keyword, "setsf"),
                ["run"] = new Token(TokenTypes.Keyword, "run"),
                ["write"] = new Token(TokenTypes.Keyword, "write"),
                ["start"] = new Token(TokenTypes.Keyword, "start"),
                ["stop"] = new Token(TokenTypes.Keyword, "stop"),
                ["wait"] = new Token(TokenTypes.Keyword, "wait"),
                ["watchstart"] = new Token(TokenTypes.Keyword, "watchstart"),
                ["watchend"] = new Token(TokenTypes.Keyword, "watchend"),
                ["abe"] = new Token(TokenTypes.Keyword, "abe"),
                ["Double"] = new Token(TokenTypes.Keyword, "Double"),
                ["helper"] = new Token(TokenTypes.Keyword, "helper"),
                ["true"] = new Token(TokenTypes.Keyword, "true"),
                ["false"] = new Token(TokenTypes.Keyword, "false"),
                ["if"] = new Token(TokenTypes.Keyword, "if"),
                ["while"] = new Token(TokenTypes.Keyword, "while"),
                ["dowhile"] = new Token(TokenTypes.Keyword, "dowhile"),
                ["throw"] = new Token(TokenTypes.Keyword, "throw"),
                ["return"] = new Token(TokenTypes.Keyword, "return"),
                ["gvfj"] = new Token(TokenTypes.Keyword, "gvfj"),
                ["class"] = new Token(TokenTypes.Keyword, "class"),
                ["invoke"] = new Token(TokenTypes.Keyword, "invoke"),
                ["function"] = new Token(TokenTypes.Keyword, "function"),
                ["read"] = new Token(TokenTypes.Keyword, "read"),
                ["import"] = new Token(TokenTypes.Keyword, "import"),
                ["anno"] = new Token(TokenTypes.Keyword, "annotation"),
                ["define"] = new Token(TokenTypes.Keyword, "define"),
                ["readline"] = new Token(TokenTypes.Keyword, "readline"),
                ["readkey"] = new Token(TokenTypes.Keyword, "readkey"),
                ["ctype"] = new Token(TokenTypes.Keyword, "ctype"),
                ["cstr"] = new Token(TokenTypes.Keyword, "cstr"),
                ["astextbox"] = new Token(TokenTypes.Keyword, "astextbox"),
                ["createData"] = new Token(TokenTypes.Keyword, "createData"),
                ["addBundingData"] = new Token(TokenTypes.Keyword, "addBundingData"),
                ["addData"] = new Token(TokenTypes.Keyword, "addData"),
                ["delData"] = new Token(TokenTypes.Keyword, "delData"),
                ["replaceData"] = new Token(TokenTypes.Keyword, "replaceData"),
                ["saveDataChanges"] = new Token(TokenTypes.Keyword, "saveDataChanges"),
                ["invokeData"] = new Token(TokenTypes.Keyword, "invokeData"),
                ["getData"] = new Token(TokenTypes.Keyword, "getData"),
                ["createInstance"] = new Token(TokenTypes.Keyword, "createInstance"),
                ["setClassVar"] = new Token(TokenTypes.Keyword, "setClassVar"),
                ["setBaseClass"] = new Token(TokenTypes.Keyword, "setBaseClass"),
                ["printMethod"] = new Token(TokenTypes.Keyword, "printMethod"),
                ["rand"] = new Token(TokenTypes.Keyword, "rand"),
                ["oldpow"] = new Token(TokenTypes.Keyword, "oldpow"),
                ["oldsin"] = new Token(TokenTypes.Keyword, "oldsin"),
                ["oldcos"] = new Token(TokenTypes.Keyword, "oldcos"),
                ["oldtan"] = new Token(TokenTypes.Keyword, "oldtan"),
                ["oldasin"] = new Token(TokenTypes.Keyword, "oldasin"),
                ["oldacos"] = new Token(TokenTypes.Keyword, "oldacos"),
                ["oldatan"] = new Token(TokenTypes.Keyword, "oldatan"),
                ["oldabs"] = new Token(TokenTypes.Keyword, "oldabs"),
                ["oldsqrt"] = new Token(TokenTypes.Keyword, "oldsqrt"),
                ["oldstrfromindex"] = new Token(TokenTypes.Keyword, "oldstrfromindex"),
                ["oldindexof"] = new Token(TokenTypes.Keyword, "oldindexof"),
                ["oldstrreplace"] = new Token(TokenTypes.Keyword, "oldstrreplace"),
                ["oldstrlen"] = new Token(TokenTypes.Keyword, "oldstrlen"),
                ["oldsubstr"] = new Token(TokenTypes.Keyword, "oldsubstr"),
                ["datalen"] = new Token(TokenTypes.Keyword, "datalen"),
                ["now"] = new Token(TokenTypes.Keyword, "now"),
                ["timeformat"] = new Token(TokenTypes.Keyword, "timeformat"),
                ["eval"] = new Token(TokenTypes.Keyword, "eval"),
                ["as"] = new Token(TokenTypes.Keyword, "as"),
                ["osinfo"] = new Token(TokenTypes.Keyword, "osinfo"),
                ["build"] = new Token(TokenTypes.Keyword, "build"),
                ["system"] = new Token(TokenTypes.Keyword, "system"),
                ["oldgetcurrentfilepath"] = new Token(TokenTypes.Keyword, "oldgetcurrentfilepath"),
                ["oldgetcurrentfolderpath"] = new Token(TokenTypes.Keyword, "oldgetcurrentfolderpath"),
                ["oldmappath"] = new Token(TokenTypes.Keyword, "oldmappath"),
                ["appquit"] = new Token(TokenTypes.Keyword, "appquit"),
                ["in"] = new Token(TokenTypes.Keyword, "in"),
                ["pause"] = new Token(TokenTypes.Keyword, "pause"),
            };
    }
}
