using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace FeiSharpStudio
{
    static class TokenKeywords
    {
        public static readonly string print = "print";
        public static readonly string printnl = "printnl";
        public static readonly string gethtml = "gethtml";
        public static readonly string _var = "var";
        public static readonly string init = "init";
        public static readonly string set = "setsf";
        public static readonly string run = "run";
        public static readonly string export = "write";
        public static readonly string start = "start";
        public static readonly string stop = "stop";
        public static readonly string wait = "wait";
        public static readonly string watchstart = "watchstart";
        public static readonly string watchend = "watchend";
        public static readonly string abe = "abe";
        public static readonly string Double = "double";
        public static readonly string helper = "helper";
        public static readonly string _true = "true";
        public static readonly string _false = "false";
        public static readonly string _if = "if";
        public static readonly string _while = "while";
        public static readonly string dowhile = "dowhile";
        public static readonly string _throw = "throw";
        public static readonly string _return = "return";
        public static readonly string getVarsFromJsonFilePath = "gvfj";
        public static readonly string readonlyclass = "class";
        public static readonly string invoke = "invoke";
        public static readonly string func = "function";
        public static readonly string read = "read";
        public static readonly string import = "import";
        public static readonly string annotation = "annotation";
        public static readonly string define = "define";
        public static readonly string readline = "readline";
        public static readonly string readkey = "readkey";
        public static readonly string ctype = "ctype";
        public static readonly string cstr = "cstr";
        public static readonly string _astextbox = "astextbox";
        public static readonly string createData = "createData";
        public static readonly string addBundingData = "addbundingdata";
        public static readonly string addData = "adddata";
        public static readonly string delData = "deldata";
        public static readonly string replaceData = "replacedata";
        public static readonly string saveDataChanges = "savedataChanges";
        public static readonly string invokeData = "invokedata";
        public static readonly string getData = "getdata";
        public static readonly string createInstance = "createinstance";
        public static readonly string setClassVar = "setclassvar";
        public static readonly string setBaseClass = "setbaseclass";
        public static readonly string printMethod = "printmethod";
        public static readonly string rand = "rand";
        public static readonly string pow = "oldpow";
        public static readonly string sin = "oldsin";
        public static readonly string cos = "oldcos";
        public static readonly string tan = "oldtan";
        public static readonly string asin = "oldasin";
        public static readonly string acos = "oldacos";
        public static readonly string atan = "oldatan";
        public static readonly string abs = "oldabs";
        public static readonly string sqrt = "oldsqrt";
        public static readonly string strfromindex = "oldstrfromindex";
        public static readonly string getindex = "oldindexof";
        public static readonly string strreplace = "oldstrreplace";
        public static readonly string strlen = "oldstrlen";
        public static readonly string substr = "oldsubstr";
        public static readonly string datalen = "datalen";
        public static readonly string now = "now";
        public static readonly string timeformat = "timeformat";
        public static readonly string eval = "eval";
        public static readonly string _as = "as";
        public static readonly string osinfo = "osinfo";
        public static readonly string tw = "build";
        public static readonly string sys = "system";
        public static readonly string getCurrentFilePath = "oldgetcurrentfilepath";
        public static readonly string getCurrentFolderPath = "oldgetcurrentfolderpath";
        public static readonly string mapPath = "oldmappath";
        public static readonly string appQuit = "appquit";
        public static readonly string classInvoke = "classinvoke";
        public static readonly string objectInvoke = "objectinvoke";
    }
}
